const JOB_ORDER_TYPES = {
  IMPORT: 'IMPORT',
  EXPORT: 'EXPORT',
  TRUCKING: 'TRUCKING',
  PROJECT: 'PROJECT'
};

const JOB_ORDER_STATUSES = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
};

// Define valid transition map for each status
const STATUS_TRANSITIONS = {
  [JOB_ORDER_STATUSES.DRAFT]: [
    JOB_ORDER_STATUSES.CONFIRMED,
    JOB_ORDER_STATUSES.CANCELLED
  ],
  [JOB_ORDER_STATUSES.CONFIRMED]: [
    JOB_ORDER_STATUSES.ASSIGNED,
    JOB_ORDER_STATUSES.CANCELLED,
    JOB_ORDER_STATUSES.DRAFT // Fallback if needed
  ],
  [JOB_ORDER_STATUSES.ASSIGNED]: [
    JOB_ORDER_STATUSES.IN_PROGRESS,
    JOB_ORDER_STATUSES.CANCELLED,
    JOB_ORDER_STATUSES.CONFIRMED
  ],
  [JOB_ORDER_STATUSES.IN_PROGRESS]: [
    JOB_ORDER_STATUSES.COMPLETED,
    JOB_ORDER_STATUSES.CANCELLED
  ],
  [JOB_ORDER_STATUSES.COMPLETED]: [
    JOB_ORDER_STATUSES.CLOSED,
    JOB_ORDER_STATUSES.CANCELLED // Sometimes operational is completed but administrative cancelled
  ],
  [JOB_ORDER_STATUSES.CLOSED]: [], // Terminal state
  [JOB_ORDER_STATUSES.CANCELLED]: [] // Terminal state
};

module.exports = {
  JOB_ORDER_TYPES,
  JOB_ORDER_STATUSES,
  STATUS_TRANSITIONS
};
